### ISSUE TITLE
Cannot create user without password

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi-okta#202] opened 2022-06-02 23:13 UTC
### What happened?

I can't create a user without setting a `password` and the `expirePasswordOnCreate` properties while both properties are optional.

### Steps to reproduce

Try creating this user:

```typescript
new okta.user.User('test', {
  login: 'foo@example.com',
  email: 'foo@example.com',
  firstName: 'Foo',
  lastName: 'Bar',
  department: 'Example',
});
 ```

### Expected Behavior

The user should be created successfully and then receive an email with a link to set his password.

### Actual Behavior

The update is aborted with the following message:

```
  okta:user:User (test):
    error: okta:user/user:User resource 'test' has a problem: Missing required argument: "expire_password_on_create": all of `expire_password_on_create,password` must be specified. Examine values at 'User.ExpirePasswordOnCreate'.
```

### Versions used

Pulumi: v3.33.2
Okta provider: 3.9.0

### Additional context

I tried creating the user with Terraform using the Okta provider, with the same arguments, and I was able to successfully create it without providing the password.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by fernandocarletti** [comment] 2022-06-03 21:41
Just tried running the tests in this repository locally and notice the issue also happens there. Checking the CI logs, Okta is not configured to run the tests: https://github.com/pulumi/pulumi-okta/runs/6581756022?check_suite_focus=true#step:20:149

**Comment by fernandocarletti** [comment] 2022-06-03 23:15
I just noticed that the `expire_password_on_create` field was added back in February. I could work around this issue by reverting the provider to `v3.6.1` which uses the terraform provider `v3.20.7`, the last one before the field was added.

**Comment by stack72** [comment] 2022-06-04 13:40
Hey @fernandocarletti 

So I see the issue here :/ Unfortuntely, this is because the Okta TF provider has the following in the schema:

```
"expire_password_on_create": {
				Type:         schema.TypeBool,
				Optional:     true,
				Default:      false,
				Description:  "If set to `true`, the user will have to change the password at the next login. This property will be used when user is being created and works only when `password` field is set",
				RequiredWith: []string{"password"},
			},
```

As this is a bool, we are sending `false` (incorrectly) by default - we need to change this in the bridge to make the schema more aware of `RequiredWith`.

I can suggest the following:


````
new okta.user.User('test', {
  login: 'foo@example.com',
  email: 'foo@example.com',
  firstName: 'Foo',
  lastName: 'Bar',
  department: 'Example',
  password: "temp",
  expirePasswordOnCreate: true,
});
```

The user will then be able to at least log in and change their password and it may unblock you?

Paul

**Comment by fernandocarletti** [comment] 2022-06-04 13:51
Hello @stack72. I tried this approach but it changes a bit the behavior in Okta. It won't notify the user when his account is created.  It just creates the User resource.

The behavior when these options are not set at all makes Okta send a welcome e-mail to the user for him to set up his password. We have around 500 users to create in the initial setup, so this welcome email is quite important.

I was playing with this provider code yesterday and assumed the issue was exactly what you mention. Maybe Terraform Bridge should have an option to "ignore if default"? Checking the verbose logs I could notice the field indeed was being set in terraform.

**Comment by stack72** [comment] 2022-06-09 12:36
Hi @fernandocarletti 

Thanks for your patience here - I have just made a quick fix here for you to remove that requiredWith semantic

I can confirm this works as follows:

old:

```
Diagnostics:
  okta:user:User (test):
    error: okta:user/user:User resource 'test' has a problem: Missing required argument: "expire_password_on_create": all of `expire_password_on_create,password` must be specified. Examine values at 'User.ExpirePasswordOnCreate'.
```

new:

```

     Type                 Name           Plan
 +   pulumi:pulumi:Stack  test-okta-dev  create
 +   └─ okta:user:User    test           create

Resources:
    + 2 to create
```

It will be released as part of v3.10.0 when we merge #203

**Closed** 2022-06-09 16:55 UTC
Labels: kind/bug

**Comment by notdodo** [comment] 2023-03-01 16:17
@stack72: I think that this bug is reintroduced in the new 3.19.0 version as I'm not able to create an user without `expire_password_on_create` and `password` parameters.
