### ISSUE TITLE
Can't create okta.PolicyRuleProfileEnrollment 

### ISSUE THREAD

**Issue by rodriguesgm** [pulumi/pulumi-okta#291] opened 2023-04-24 20:03 UTC
### What happened?

When trying to create a custom Policy Profile Enrollment Rule I got an error, this happens if I set `uiSchemaId` or not.

I'm using `@pulumi/okta:3.22.0`.

### Expected Behavior

Expect that the Policy Profile Enrollment Rule to be created.

### Steps to reproduce

```
export const customPolicy = new okta.PolicyProfileEnrollment('custom-policy', {
  name: 'Custom policy',
  status: 'ACTIVE',
});

export const customAppPolicy = new okta.PolicyProfileEnrollmentApps('custom-policy-app', {
  policyId: customPolicy.id,
  apps: [
    // Add app in here
  ],
});

export const customPolicyRule = new okta.PolicyRuleProfileEnrollment('custom-policy-rule', {
  policyId: customPolicy.id,
  unknownUserAction: 'DENY',
  access: 'ALLOW',
  emailVerification: false,
//  uiSchemaId: this is the property raising errors, even if I remove this property or if I set the oktaId returned by the api /api/v1/meta/uischemas, it does not work. I got the same error
  profileAttributes: [{
    label: 'First name',
    name: 'firstName',
    required: true,
  }, {
    label: 'Last name',
    name: 'lastName',
    required: true,
  }, {
    label: 'Primary email',
    name: 'email',
    required: true,
  }],
});
```

### Output of `pulumi about`

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/10141664/234102762-7a6d3889-da5b-4a54-bb9c-ceb156e11635.png">

```
failed to create profile enrollment policy rule: the API returned an error: Api validation failed: actions.profileEnrollment.uiSchemaId. 
Causes: errorSummary: actions.profileEnrollment.uiSchemaId: The rule could not be created or updated because the uiSchemaId field in the action contained an invalid value or was incorrectly formatted
```

### Additional context

May be related to https://github.com/okta/terraform-provider-okta/issues/1213

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-04-24 20:49
Hi @rodriguesgm. Thanks for opening an issue. 

Can you provide the output of running `pulumi about` in the stack where you experienced this issue? This helps us figure out the right set of versions to reproduce the bug with.

Does the schema you are hardcoding look like `uis4abjqkkKXVPGAU0g7`?

**Comment by rodriguesgm** [comment] 2023-04-25 10:25
hey @iwahbe thanks for the help

Yes the schema id is something like you said.

```
pulumi about
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
CLI          
Version      3.51.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
okta    3.22.0

Host     
OS       darwin
Version  10.15.7
Arch     x86_64

This project is written in nodejs: executable='/Users/Guilherme.Machadoro/.nvm/versions/node/v16.20.0/bin/node' version='v16.20.0'

Dependencies:
NAME                              VERSION
eslint-plugin-promise             6.1.1
eslint                            8.28.0
@pulumi/okta                      3.22.0
@types/eslint                     8.4.10
@typescript-eslint/parser         5.45.0
ejs                               3.1.8
eslint-plugin-import              2.26.0
typescript                        4.9.3
@types/ejs                        3.1.1
@typescript-eslint/eslint-plugin  5.45.0
eslint-config-standard            17.0.0
eslint-plugin-node                11.1.0
eslint-plugin-standard            4.1.0
```

**Comment by mikhailshilkov** [comment] 2023-05-08 21:38
@iwahbe Could you please take another look to triage the issue further?

**Comment by aq17** [comment] 2023-06-20 22:51
Hi @rodriguesgm , were you able to solve your issue by upgrading to the latest provider?

**Comment by rodriguesgm** [comment] 2023-06-29 13:34
yes, I can set the `uiSchemaId` in the latest version

thanks

**Comment by iwahbe** [comment] 2023-06-29 14:38
Since this works in the latest version, I'm closing it.

**Closed by iwahbe** 2023-06-29 14:38 UTC
Labels: kind/bug, awaiting-upstream, resolution/fixed
